site_name: CTX-EOR
theme:
  name: material
  logo: logo.png
  favicon: logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Why CTX-EOR: why-ctx.md
  - How It Works: how-it-works.md
  - Trial Hiring: trial-hiring.md
  - Structured Evaluation: structured-evaluation.md
  - Compliance: compliance.md
  - Services:
      - EOR: eor.md
      - Payroll: payroll.md
      - Benefits: benefits.md
  - About Us: about.md
  - Contact: contact.md
