site_name: CTX-EOR
site_description: Trial Hiring & Employer of Record for U.S. Companies
site_author: CTX-EOR Team

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
  logo: logo.png
  favicon: logo.png

palette:
  - scheme: default
    primary: blue
    accent: teal
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary: blue
    accent: teal
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

nav:
  - Home: index.md
  - Why CTX-EOR: why-ctx.md
  - Employer Overview: employer-overview.md
  - How It Works: how-it-works.md
  - Trial Hiring: trial-hiring.md
  - Trial Builder: trial-builder.md
  - Fine-Tune Production Worker: fine-tune-production-worker.md
  - Evaluation-Checkpoints: evaluation-checkpoints.md
  - Save Trial: save-and-share.md
  - Trial Dashboard: trial-dashboard.md
  - Trial Details: trial-details.md
  - Trial Builder: trial-builder-step1.md
  - Role Template: trial-builder-step2.md
  - Customize Role: trial-builder-step3.md
  - Set Timeline & Manager: trial-builder-step4.md
  - Worksite & Schedule: trial-builder-step5.md
  - Screening & Background Requirements: trial-builder-step6.md
  - Pay & Benefits Setup: trial-builder-step7.md
  - Employer Cost Estimate: trial-builder-step8.md
  - Trial Timeline & Check-ins: trial-builder-step9.md
  - Finalize & Save: trial-builder-step10.md
  - Structured Evaluation: structured-evaluation.md
  - Compliance: compliance.md
  - The CTX Platform: platform.md
  - Services:
      - Overview: services-overview.md
      - EOR: eor.md
      - Payroll: payroll.md
      - Benefits: benefits.md
  - Pricing: pricing.md
  - Who It’s For: who-its-for.md
  - Industries We Support: industries.md
  - Proof It Works: proof.md  
  - About Us: about.md
  - Contact: contact.md
